import type { DcfTopology } from '../types/dcf';

function sanitizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '_').replace(/_+/g, '_').replace(/^_+|_+$/g, '');
}

function escapeHcl(value: string): string {
  // Escape double quotes and disable HCL interpolation by escaping ${ sequences
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$\{/g, '\\${');
}

export function generateTerraform(topology: DcfTopology): string {
  const lines: string[] = [];

  lines.push(`# Generated by Aviatrix DCF Visualizer`);
  lines.push(`# Terraform configuration for Aviatrix Distributed Cloud Firewall`);
  lines.push(`# Provider: AviatrixSystems/aviatrix (>= 2.22.0)`);
  lines.push('');
  lines.push(`terraform {`);
  lines.push(`  required_providers {`);
  lines.push(`    aviatrix = {`);
  lines.push(`      source  = "AviatrixSystems/aviatrix"`);
  lines.push(`      version = ">= 2.22.0"`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push('');
  lines.push(`# ============================================`);
  lines.push(`# Smart Groups`);
  lines.push(`# ============================================`);
  lines.push('');

  // Smart Groups
  topology.smartGroups.forEach((sg) => {
    if (sg.id === 'sg-internet') return; // Skip special groups
    const resourceName = sanitizeName(sg.name);
    lines.push(`resource "aviatrix_smart_group" "${resourceName}" {`);
    lines.push(`  name = "${escapeHcl(sg.name)}"`);
    lines.push('');
    lines.push(`  selector {`);
    sg.criteria.forEach((c) => {
      lines.push(`    match_expressions {`);
      lines.push(`      type = "vm"`);
      lines.push(`      key  = "${escapeHcl(c.key)}"`);
      lines.push(`      val  = "${escapeHcl(c.value)}"`);
      lines.push(`    }`);
    });
    lines.push(`  }`);
    lines.push(`}`);
    lines.push('');
  });

  // Threat Groups (reference only)
  if (topology.threatGroups.length > 0) {
    lines.push(`# ============================================`);
    lines.push(`# Threat Groups (External Groups)`);
    lines.push(`# ============================================`);
    lines.push(`# Note: Configure ThreatGroups/GeoGroups via Controller UI or`);
    lines.push(`#       aviatrix_smart_group with external group selectors.`);
    lines.push('');
  }

  // DCF Policies
  lines.push(`# ============================================`);
  lines.push(`# Distributed Cloud Firewall Policies`);
  lines.push(`# ============================================`);
  lines.push('');
  lines.push(`resource "aviatrix_distributed_firewalling_policy_list" "dcf_policies" {`);

  topology.policies.forEach((pol) => {
    const srcName = sanitizeName(topology.smartGroups.find((g) => g.id === pol.srcGroupId)?.name || pol.srcGroupId);
    const dstName = sanitizeName(topology.smartGroups.find((g) => g.id === pol.dstGroupId)?.name || pol.dstGroupId);

    lines.push(`  policies {`);
    lines.push(`    # ${escapeHcl(pol.name)} (Priority: ${pol.priority})`);
    lines.push(`    name     = "${escapeHcl(pol.name)}"`);
    lines.push(`    priority = ${pol.priority}`);
    lines.push(`    action   = "${pol.action === 'allow' ? 'PERMIT' : 'DENY'}"`);
    lines.push(`    protocol = "${pol.protocol.toUpperCase()}"`);
    if (pol.ports && pol.ports !== 'any') {
      lines.push(`    port_ranges = [${pol.ports.split(',').map((p) => `"${escapeHcl(p.trim())}"`).join(', ')}]`);
    }
    lines.push(`    logging = ${pol.logging}`);
    if (pol.decrypt) {
      lines.push(`    decrypt = true`);
    }
    lines.push(`    src_smart_groups = [aviatrix_smart_group.${srcName}.uuid]`);
    lines.push(`    dst_smart_groups = [aviatrix_smart_group.${dstName}.uuid]`);
    if (pol.threatGroup) {
      lines.push(`    # threat_group = "${escapeHcl(pol.threatGroup)}"`);
    }
    if (pol.geoGroup) {
      lines.push(`    # geo_group = "${escapeHcl(pol.geoGroup)}"`);
    }
    lines.push(`  }`);
  });

  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}

export function downloadTerraform(topology: DcfTopology): void {
  const content = generateTerraform(topology);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'aviatrix_dcf.tf';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
