import { describe, it, expect } from 'vitest';
import { generateTerraform, generateTerraformModule } from './terraformExport';
import { demoTopology } from '../data/demoTopology';

// Expected HCL output for the demo topology. Built by tracing the generator
// (single source of truth for the snapshot). Using `toBe` against an inline
// string gives the same "human-readable snapshot in the test file" property
// as `toMatchInlineSnapshot()` while remaining trivial to review and update.
const EXPECTED_DEMO_HCL = `# Generated by Aviatrix DCF Visualizer
# Terraform configuration for Aviatrix Distributed Cloud Firewall
# Provider: AviatrixSystems/aviatrix (>= 2.22.0)

terraform {
  required_providers {
    aviatrix = {
      source  = "AviatrixSystems/aviatrix"
      version = ">= 2.22.0"
    }
  }
}

# ============================================
# Smart Groups
# ============================================

resource "aviatrix_smart_group" "web_tier" {
  name = "Web Tier"

  selector {
    match_expressions {
      type = "vm"
      key  = "tag:app-tier"
      val  = "web"
    }
  }
}

resource "aviatrix_smart_group" "app_tier" {
  name = "App Tier"

  selector {
    match_expressions {
      type = "vm"
      key  = "tag:app-tier"
      val  = "app"
    }
  }
}

resource "aviatrix_smart_group" "database_tier" {
  name = "Database Tier"

  selector {
    match_expressions {
      type = "vm"
      key  = "tag:app-tier"
      val  = "db"
    }
  }
}

resource "aviatrix_smart_group" "bastion_hosts" {
  name = "Bastion Hosts"

  selector {
    match_expressions {
      type = "vm"
      key  = "tag:role"
      val  = "bastion"
    }
  }
}

resource "aviatrix_smart_group" "monitoring" {
  name = "Monitoring"

  selector {
    match_expressions {
      type = "vm"
      key  = "tag:service"
      val  = "monitoring"
    }
  }
}

resource "aviatrix_smart_group" "dev_workloads" {
  name = "Dev Workloads"

  selector {
    match_expressions {
      type = "vm"
      key  = "tag:env"
      val  = "dev"
    }
  }
  selector {
    match_expressions {
      type = "subnet"
      cidr = "10.3.0.0/16"
    }
  }
}

# ============================================
# Web Groups
# ============================================
# NOTE: Aviatrix provider does not have a native "aviatrix_web_group" resource.
#       Configure web groups via Controller UI or use aviatrix_fqdn if applicable.
# TODO: Map these web groups to appropriate Terraform resources or data sources.

# WebGroup: SaaS Allowlist
#   FQDNs: *.salesforce.com, *.slack.com, *.github.com

# WebGroup: OS Updates
#   FQDNs: *.windowsupdate.com, *.ubuntu.com, *.amazonaws.com

# ============================================
# Threat Groups (External Groups)
# ============================================
# Note: Configure ThreatGroups via Controller UI or
#       aviatrix_smart_group with external group selectors.

# ============================================
# Geo Groups (External Groups)
# ============================================
# Note: Configure GeoGroups via Controller UI.

# ============================================
# Distributed Cloud Firewall Policies
# ============================================

resource "aviatrix_distributed_firewalling_policy_list" "dcf_policies" {

  policies {
    # Allow Web to App (Priority: 100)
    name     = "Allow Web to App"
    priority = 100
    action   = "PERMIT"
    enforce  = true
    protocol = "TCP"
    port_ranges = ["8080", "8443"]
    logging = true
    src_smart_groups = [aviatrix_smart_group.web_tier.name]
    dst_smart_groups = [aviatrix_smart_group.app_tier.name]
  }

  policies {
    # Allow App to DB (Priority: 110)
    name     = "Allow App to DB"
    priority = 110
    action   = "PERMIT"
    enforce  = true
    protocol = "TCP"
    port_ranges = ["3306", "5432"]
    logging = true
    src_smart_groups = [aviatrix_smart_group.app_tier.name]
    dst_smart_groups = [aviatrix_smart_group.database_tier.name]
  }

  policies {
    # Deny Web to DB (Priority: 120)
    name     = "Deny Web to DB"
    priority = 120
    action   = "DENY"
    enforce  = true
    protocol = "ANY"
    logging = true
    src_smart_groups = [aviatrix_smart_group.web_tier.name]
    dst_smart_groups = [aviatrix_smart_group.database_tier.name]
  }

  policies {
    # Allow Bastion to All (Priority: 90)
    name     = "Allow Bastion to All"
    priority = 90
    action   = "PERMIT"
    enforce  = true
    protocol = "TCP"
    port_ranges = ["22", "3389"]
    logging = true
    src_smart_groups = [aviatrix_smart_group.bastion_hosts.name]
    dst_smart_groups = []
  }

  policies {
    # Allow Monitoring Egress (Priority: 130)
    name     = "Allow Monitoring Egress"
    priority = 130
    action   = "PERMIT"
    enforce  = true
    protocol = "TCP"
    port_ranges = ["443"]
    logging = true
    src_smart_groups = [aviatrix_smart_group.monitoring.name]
    dst_smart_groups = [aviatrix_smart_group.internet.name]
  }

  policies {
    # Deny Dev to Prod (Priority: 50)
    name     = "Deny Dev to Prod"
    priority = 50
    action   = "DENY"
    enforce  = true
    protocol = "ANY"
    logging = true
    src_smart_groups = [aviatrix_smart_group.dev_workloads.name]
    dst_smart_groups = [aviatrix_smart_group.app_tier.name]
  }

  policies {
    # Allow Dev Internal (Priority: 140)
    name     = "Allow Dev Internal"
    priority = 140
    action   = "PERMIT"
    enforce  = true
    protocol = "ANY"
    logging = false
    src_smart_groups = [aviatrix_smart_group.dev_workloads.name]
    dst_smart_groups = [aviatrix_smart_group.dev_workloads.name]
  }

  policies {
    # Web Egress with ThreatBlock (Priority: 150)
    name     = "Web Egress with ThreatBlock"
    priority = 150
    action   = "PERMIT"
    enforce  = true
    protocol = "TCP"
    port_ranges = ["443"]
    logging = true
    decrypt = true
    src_smart_groups = [aviatrix_smart_group.web_tier.name]
    dst_smart_groups = [aviatrix_smart_group.internet.name]
    threat_group = "tg-malware"
  }

  policies {
    # GeoBlock Non-US (Priority: 160)
    name     = "GeoBlock Non-US"
    priority = 160
    action   = "DENY"
    enforce  = true
    protocol = "ANY"
    logging = true
    src_smart_groups = [aviatrix_smart_group.internet.name]
    dst_smart_groups = [aviatrix_smart_group.web_tier.name]
    geo_group = "gg-non-us"
  }

  policies {
    # Default Deny All (Priority: 9999)
    name     = "Default Deny All"
    priority = 9999
    action   = "DENY"
    enforce  = true
    protocol = "ANY"
    logging = false
    src_smart_groups = []
    dst_smart_groups = []
  }

  policies {
    # Learned Routes from Peer (Priority: 10)
    name     = "Learned Routes from Peer"
    priority = 10
    action   = "PERMIT"
    enforce  = true
    protocol = "ANY"
    logging = false
    src_smart_groups = []
    dst_smart_groups = []
  }

  policies {
    # SaaS Egress via WebGroup (Priority: 70)
    name     = "SaaS Egress via WebGroup"
    priority = 70
    action   = "PERMIT"
    enforce  = true
    protocol = "TCP"
    port_ranges = ["443"]
    logging = true
    src_smart_groups = [aviatrix_smart_group.app_tier.name]
    dst_smart_groups = [aviatrix_smart_group.internet.name]
    # web_groups = ["SaaS Allowlist"]  # TODO: reference once web group resources are defined
  }

}
`;

describe('generateTerraform', () => {
  it('matches the locked-in snapshot for the demo topology', () => {
    // Hand-rolled inline snapshot: an explicit `toBe` against the inline
    // literal above keeps the expected output human-reviewable in this test
    // file (the PLAN.md spirit of `toMatchInlineSnapshot`).
    expect(generateTerraform(demoTopology)).toBe(EXPECTED_DEMO_HCL);
  });

  it('is deterministic — calling twice with the same input yields the same output', () => {
    expect(generateTerraform(demoTopology)).toBe(generateTerraform(demoTopology));
  });

  it('does not emit smart_group resources for sg-any or sg-internet', () => {
    const hcl = generateTerraform(demoTopology);
    expect(hcl).not.toContain('resource "aviatrix_smart_group" "internet" {');
    expect(hcl).not.toContain('resource "aviatrix_smart_group" "any" {');
  });
});

describe('generateTerraformModule', () => {
  const out = generateTerraformModule(demoTopology);

  it('emits a single module call against terraform-aviatrix-modules/dcf-framework/aviatrix', () => {
    expect(out).toContain('module "dcf" {');
    expect(out).toContain('source  = "terraform-aviatrix-modules/dcf-framework/aviatrix"');
    expect(out).toContain('version = "~> 1.0"');
  });

  it('emits smart_groups as a map keyed by sanitized name (not by id)', () => {
    expect(out).toContain('smart_groups = {');
    // demo includes "Web Tier" — sanitized = "web-tier"
    expect(out).toContain('web-tier = {');
    expect(out).toContain('name = "Web Tier"');
    // sg-any and sg-internet are skipped
    expect(out).not.toContain('any = {');
    expect(out).not.toContain('internet = {');
  });

  it('emits web_groups with snifilter selectors', () => {
    expect(out).toContain('web_groups = {');
    // demo includes "SaaS Allowlist" with *.salesforce.com
    expect(out).toContain('{ snifilter = "*.salesforce.com" },');
  });

  it('emits a single default ruleset with all policies as rules', () => {
    expect(out).toContain('rulesets = {');
    expect(out).toContain('default = {');
    expect(out).toContain('action   = "PERMIT"');
    expect(out).toContain('action   = "DENY"');
  });

  it('references smart_groups in rules by map key, not by id', () => {
    // Web -> App allow rule uses sanitized names, not sg-web / sg-app
    expect(out).toContain('src_smart_groups = ["web-tier"]');
    expect(out).toContain('dst_smart_groups = ["app-tier"]');
    expect(out).not.toContain('"sg-web"');
    expect(out).not.toContain('"sg-app"');
  });

  it('uses "any" / "internet" sentinels for the special SmartGroup IDs', () => {
    // demo's pol-4 is bastion → any
    expect(out).toContain('dst_smart_groups = ["any"]');
    // demo's pol-5 is monitoring → internet
    expect(out).toContain('dst_smart_groups = ["internet"]');
  });

  it('maps decrypt=true to DECRYPT_REQUIRED', () => {
    // demo's pol-8 has decrypt: true
    expect(out).toContain('decrypt_policy = "DECRYPT_REQUIRED"');
  });

  it('emits port_ranges as a list of {lo, hi?} objects parsed from the comma-separated ports field', () => {
    // demo's pol-1 has ports: '8080,8443'
    expect(out).toContain('{ lo = 8080 },');
    expect(out).toContain('{ lo = 8443 },');
  });

  it('emits ThreatGroups and GeoGroups as raw resources alongside the module call', () => {
    expect(out).toContain('resource "aviatrix_threat_group"');
    expect(out).toContain('resource "aviatrix_geo_group"');
  });

  it('is deterministic — calling twice with the same input yields the same output', () => {
    expect(generateTerraformModule(demoTopology)).toBe(generateTerraformModule(demoTopology));
  });

  it('surfaces a warning header when any policy has enforcement disabled', () => {
    const topoWithDisabled = {
      ...demoTopology,
      policies: demoTopology.policies.map((p, i) => i === 0 ? { ...p, enforcement: false } : p),
    };
    const out2 = generateTerraformModule(topoWithDisabled);
    expect(out2).toMatch(/# WARNING:.*enforcement disabled/i);
  });
});
