import type { DcfPolicyModel, SmartGroup, WebGroup, SmartGroupCriteria } from '../types/dcf';
import {
  parsePortString,
  decryptToEnum,
  actionToProviderString,
  protocolToProviderString,
  sanitizeMapKey,
} from './terraform/moduleHelpers';

function sanitizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '_').replace(/_+/g, '_').replace(/^_+|_+$/g, '');
}

function escapeHcl(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$\{/g, '\\${');
}

function getSmartGroupName(topology: DcfPolicyModel, groupId: string): string | null {
  if (groupId === 'sg-any') return null;
  const sg = topology.smartGroups.find((g) => g.id === groupId);
  return sg?.name || null;
}

export function generateTerraform(topology: DcfPolicyModel): string {
  const lines: string[] = [];

  lines.push(`# Generated by Aviatrix DCF Visualizer`);
  lines.push(`# Terraform configuration for Aviatrix Distributed Cloud Firewall`);
  lines.push(`# Provider: AviatrixSystems/aviatrix (>= 2.22.0)`);
  lines.push('');
  lines.push(`terraform {`);
  lines.push(`  required_providers {`);
  lines.push(`    aviatrix = {`);
  lines.push(`      source  = "AviatrixSystems/aviatrix"`);
  lines.push(`      version = ">= 2.22.0"`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push('');

  // ============================================
  // Smart Groups
  // ============================================
  const exportableSmartGroups = topology.smartGroups.filter(
    (sg) => sg.id !== 'sg-internet' && sg.id !== 'sg-any'
  );

  if (exportableSmartGroups.length > 0) {
    lines.push(`# ============================================`);
    lines.push(`# Smart Groups`);
    lines.push(`# ============================================`);
    lines.push('');

    exportableSmartGroups.forEach((sg) => {
      const resourceName = sanitizeName(sg.name);
      lines.push(`resource "aviatrix_smart_group" "${resourceName}" {`);
      lines.push(`  name = "${escapeHcl(sg.name)}"`);
      lines.push('');

      if (sg.matchType === 'any') {
        sg.criteria.forEach((c) => {
          lines.push(`  selector {`);
          lines.push(`    match_expressions {`);
          if (c.type === 'vm') {
            lines.push(`      type = "vm"`);
            if (c.key) {
              lines.push(`      key  = "tag:${escapeHcl(c.key)}"`);
            }
            if (c.value !== undefined) {
              lines.push(`      val  = "${escapeHcl(c.value)}"`);
            }
          } else if (c.type === 'subnet') {
            lines.push(`      type = "subnet"`);
            if (c.cidr) {
              lines.push(`      cidr = "${escapeHcl(c.cidr)}"`);
            }
          }
          lines.push(`    }`);
          lines.push(`  }`);
        });
      } else {
        lines.push(`  selector {`);
        sg.criteria.forEach((c) => {
          lines.push(`    match_expressions {`);
          if (c.type === 'vm') {
            lines.push(`      type = "vm"`);
            if (c.key) {
              lines.push(`      key  = "tag:${escapeHcl(c.key)}"`);
            }
            if (c.value !== undefined) {
              lines.push(`      val  = "${escapeHcl(c.value)}"`);
            }
          } else if (c.type === 'subnet') {
            lines.push(`      type = "subnet"`);
            if (c.cidr) {
              lines.push(`      cidr = "${escapeHcl(c.cidr)}"`);
            }
          }
          lines.push(`    }`);
        });
        lines.push(`  }`);
      }

      lines.push(`}`);
      lines.push('');
    });
  }

  // ============================================
  // Web Groups
  // ============================================
  if (topology.webGroups.length > 0) {
    lines.push(`# ============================================`);
    lines.push(`# Web Groups`);
    lines.push(`# ============================================`);
    lines.push(`# NOTE: Aviatrix provider does not have a native "aviatrix_web_group" resource.`);
    lines.push(`#       Configure web groups via Controller UI or use aviatrix_fqdn if applicable.`);
    lines.push(`# TODO: Map these web groups to appropriate Terraform resources or data sources.`);
    lines.push('');

    topology.webGroups.forEach((wg) => {
      lines.push(`# WebGroup: ${escapeHcl(wg.name)}`);
      lines.push(`#   FQDNs: ${wg.fqdns.map((f) => escapeHcl(f)).join(', ')}`);
      lines.push('');
    });
  }

  // ============================================
  // Threat Groups (reference only)
  // ============================================
  if (topology.threatGroups.length > 0) {
    lines.push(`# ============================================`);
    lines.push(`# Threat Groups (External Groups)`);
    lines.push(`# ============================================`);
    lines.push(`# Note: Configure ThreatGroups via Controller UI or`);
    lines.push(`#       aviatrix_smart_group with external group selectors.`);
    lines.push('');
  }

  // ============================================
  // Geo Groups (reference only)
  // ============================================
  if (topology.geoGroups.length > 0) {
    lines.push(`# ============================================`);
    lines.push(`# Geo Groups (External Groups)`);
    lines.push(`# ============================================`);
    lines.push(`# Note: Configure GeoGroups via Controller UI.`);
    lines.push('');
  }

  // ============================================
  // DCF Policies
  // ============================================
  lines.push(`# ============================================`);
  lines.push(`# Distributed Cloud Firewall Policies`);
  lines.push(`# ============================================`);
  lines.push('');
  lines.push(`resource "aviatrix_distributed_firewalling_policy_list" "dcf_policies" {`);
  lines.push('');

  topology.policies.forEach((pol) => {
    const srcName = getSmartGroupName(topology, pol.srcGroupId);
    const dstName = getSmartGroupName(topology, pol.dstGroupId);

    const srcExcludeNames = (pol.srcExcludeGroupIds || [])
      .map((id) => getSmartGroupName(topology, id))
      .filter((n): n is string => n !== null);
    const dstExcludeNames = (pol.dstExcludeGroupIds || [])
      .map((id) => getSmartGroupName(topology, id))
      .filter((n): n is string => n !== null);

    const actionMap: Record<string, string> = {
      allow: 'PERMIT',
      deny: 'DENY',
      learned: 'LEARNED',
    };

    lines.push(`  policies {`);
    lines.push(`    # ${escapeHcl(pol.name)} (Priority: ${pol.priority})`);
    lines.push(`    name     = "${escapeHcl(pol.name)}"`);
    lines.push(`    priority = ${pol.priority}`);
    lines.push(`    action   = "${actionMap[pol.action] || 'DENY'}"`);
    lines.push(`    enforce  = ${pol.enforcement !== false}`);
    lines.push(`    protocol = "${pol.protocol.toUpperCase()}"`);
    if (pol.ports && pol.ports !== 'any') {
      lines.push(`    port_ranges = [${pol.ports.split(',').map((p) => `"${escapeHcl(p.trim())}"`).join(', ')}]`);
    }
    lines.push(`    logging = ${pol.logging}`);
    if (pol.decrypt) {
      lines.push(`    decrypt = true`);
    }

    if (srcName) {
      lines.push(`    src_smart_groups = [aviatrix_smart_group.${sanitizeName(srcName)}.name]`);
    } else {
      lines.push(`    src_smart_groups = []`);
    }

    if (dstName) {
      lines.push(`    dst_smart_groups = [aviatrix_smart_group.${sanitizeName(dstName)}.name]`);
    } else {
      lines.push(`    dst_smart_groups = []`);
    }

    if (srcExcludeNames.length > 0) {
      lines.push(
        `    src_exclude_smart_groups = [${srcExcludeNames.map((n) => `aviatrix_smart_group.${sanitizeName(n)}.name`).join(', ')}]`
      );
    }

    if (dstExcludeNames.length > 0) {
      lines.push(
        `    dst_exclude_smart_groups = [${dstExcludeNames.map((n) => `aviatrix_smart_group.${sanitizeName(n)}.name`).join(', ')}]`
      );
    }

    if (pol.webGroupIds && pol.webGroupIds.length > 0) {
      const webGroupNames = pol.webGroupIds
        .map((id) => topology.webGroups.find((wg) => wg.id === id)?.name)
        .filter((n): n is string => !!n);
      if (webGroupNames.length > 0) {
        lines.push(`    # web_groups = [${webGroupNames.map((n) => `"${escapeHcl(n)}"`).join(', ')}]  # TODO: reference once web group resources are defined`);
      }
    }

    if (pol.threatGroup) {
      lines.push(`    threat_group = "${escapeHcl(pol.threatGroup)}"`);
    }
    if (pol.geoGroup) {
      lines.push(`    geo_group = "${escapeHcl(pol.geoGroup)}"`);
    }

    lines.push(`  }`);
    lines.push('');
  });

  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Module-style Terraform export — emits a single
 * `module "terraform-aviatrix-modules/dcf-framework/aviatrix"` block with
 * SmartGroups / WebGroups / a single ruleset, plus raw `aviatrix_threat_group`
 * and `aviatrix_geo_group` resources for the entities the module doesn't
 * cover. This is the default style in the Export modal; the legacy
 * `generateTerraform` (raw provider resources) stays available behind the
 * style toggle.
 *
 * Schema reference: https://github.com/terraform-aviatrix-modules/terraform-aviatrix-dcf-framework/blob/main/variables.tf
 */
export const DCF_MODULE_VERSION_CONSTRAINT = '~> 1.0';

export function generateTerraformModule(topology: DcfPolicyModel): string {
  const lines: string[] = [];

  lines.push(`# Generated by Aviatrix DCF Visualizer (module-style export)`);
  lines.push(`# Module: terraform-aviatrix-modules/dcf-framework/aviatrix ${DCF_MODULE_VERSION_CONSTRAINT}`);
  lines.push(`# Customize the version pin to match the provider in your repo.`);
  lines.push('');

  // Stable map-key assignment: a SmartGroup/WebGroup's sanitized name is used
  // as both the module map key AND the cross-reference value in ruleset rules.
  // sg-internet and sg-any are special: the module doesn't manage them, so we
  // pass UUIDs through verbatim for rule references.
  const sgKey = new Map<string, string>();
  const sgKeySet = new Set<string>();
  const exportableSGs = topology.smartGroups.filter((g) => g.id !== 'sg-internet' && g.id !== 'sg-any');
  for (const sg of exportableSGs) {
    const key = sanitizeMapKey(sg.name, sgKeySet);
    sgKeySet.add(key);
    sgKey.set(sg.id, key);
  }

  const wgKey = new Map<string, string>();
  const wgKeySet = new Set<string>();
  for (const wg of topology.webGroups) {
    const key = sanitizeMapKey(wg.name, wgKeySet);
    wgKeySet.add(key);
    wgKey.set(wg.id, key);
  }

  // Warn at the top about lossy mappings.
  const enforcementDisabled = topology.policies.filter((p) => p.enforcement === false);
  if (enforcementDisabled.length > 0) {
    lines.push(`# WARNING: ${enforcementDisabled.length} policy${enforcementDisabled.length === 1 ? '' : 'ies'} in your model have enforcement disabled,`);
    lines.push(`# but the DCF Framework module does not expose a per-rule enforce field.`);
    lines.push(`# Those rules below will apply as ENFORCED. Switch to the Raw resources export`);
    lines.push(`# style if you need to preserve enforcement=false state.`);
    lines.push(`# Affected: ${enforcementDisabled.map((p) => p.name).join(', ')}`);
    lines.push('');
  }

  // -----------------------------------------------------------------
  // module "dcf"
  // -----------------------------------------------------------------
  lines.push(`module "dcf" {`);
  lines.push(`  source  = "terraform-aviatrix-modules/dcf-framework/aviatrix"`);
  lines.push(`  version = "${DCF_MODULE_VERSION_CONSTRAINT}"`);
  lines.push('');

  // ---- smart_groups ----
  if (exportableSGs.length > 0) {
    lines.push(`  smart_groups = {`);
    for (const sg of exportableSGs) {
      const key = sgKey.get(sg.id)!;
      lines.push(`    ${key} = {`);
      lines.push(`      name = "${escapeHcl(sg.name)}"`);
      lines.push(`      selector = [`);
      for (const entry of buildSmartGroupSelectorEntries(sg)) {
        lines.push(`        ${entry},`);
      }
      lines.push(`      ]`);
      lines.push(`    }`);
    }
    lines.push(`  }`);
    lines.push('');
  }

  // ---- web_groups ----
  if (topology.webGroups.length > 0) {
    lines.push(`  web_groups = {`);
    for (const wg of topology.webGroups) {
      const key = wgKey.get(wg.id)!;
      lines.push(`    ${key} = {`);
      lines.push(`      name = "${escapeHcl(wg.name)}"`);
      lines.push(`      selector = [`);
      for (const fqdn of wg.fqdns) {
        // v1: every fqdn pattern goes in as snifilter (TLS SNI). Users who
        // need urlfilter (full-URL match) should hand-edit. We can't
        // distinguish snifilter vs urlfilter from our flat fqdns array.
        lines.push(`        { snifilter = "${escapeHcl(fqdn)}" },`);
      }
      lines.push(`      ]`);
      lines.push(`    }`);
    }
    lines.push(`  }`);
    lines.push('');
  }

  // ---- rulesets ----
  if (topology.policies.length > 0) {
    lines.push(`  rulesets = {`);
    lines.push(`    default = {`);
    lines.push(`      rules = [`);
    const sorted = [...topology.policies].sort((a, b) => a.priority - b.priority);
    for (const pol of sorted) {
      lines.push(`        {`);
      lines.push(`          name     = "${escapeHcl(pol.name)}"`);
      lines.push(`          action   = "${actionToProviderString(pol.action)}"`);
      lines.push(`          protocol = "${protocolToProviderString(pol.protocol)}"`);
      lines.push(`          priority = ${pol.priority}`);
      lines.push(`          src_smart_groups = ${ruleGroupRef(pol.srcGroupId, sgKey)}`);
      lines.push(`          dst_smart_groups = ${ruleGroupRef(pol.dstGroupId, sgKey)}`);
      const ports = parsePortString(pol.ports);
      if (ports.length > 0) {
        lines.push(`          port_ranges = [`);
        for (const r of ports) {
          if (r.hi !== undefined) lines.push(`            { lo = ${r.lo}, hi = ${r.hi} },`);
          else                     lines.push(`            { lo = ${r.lo} },`);
        }
        lines.push(`          ]`);
      }
      if (pol.webGroupIds && pol.webGroupIds.length > 0) {
        const wgs = pol.webGroupIds.map((id) => `"${wgKey.get(id) ?? id}"`).join(', ');
        lines.push(`          web_groups = [${wgs}]`);
      }
      lines.push(`          decrypt_policy = "${decryptToEnum(pol.decrypt)}"`);
      lines.push(`          logging = ${pol.logging === true}`);
      lines.push(`        },`);
    }
    lines.push(`      ]`);
    lines.push(`    }`);
    lines.push(`  }`);
  }

  lines.push(`}`);
  lines.push('');

  // -----------------------------------------------------------------
  // Raw resources for entities the module doesn't cover.
  // -----------------------------------------------------------------
  if (topology.threatGroups.length > 0) {
    lines.push(`# ThreatGroups — module doesn't expose these, emitting as raw resources.`);
    for (const tg of topology.threatGroups) {
      const res = sanitizeName(tg.name);
      lines.push(`resource "aviatrix_threat_group" "${res}" {`);
      lines.push(`  name     = "${escapeHcl(tg.name)}"`);
      lines.push(`  category = "${escapeHcl(tg.category)}"`);
      lines.push(`}`);
      lines.push('');
    }
  }

  if (topology.geoGroups.length > 0) {
    lines.push(`# GeoGroups — module doesn't expose these, emitting as raw resources.`);
    for (const gg of topology.geoGroups) {
      const res = sanitizeName(gg.name);
      lines.push(`resource "aviatrix_geo_group" "${res}" {`);
      lines.push(`  name      = "${escapeHcl(gg.name)}"`);
      const countries = gg.countries.map((c) => `"${escapeHcl(c)}"`).join(', ');
      lines.push(`  countries = [${countries}]`);
      lines.push(`}`);
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Render a ruleset's smart-group reference (single id) into the module's
 * `list(string)` shape. Special cases:
 *   - sg-any → ["any"]  (the module recognizes "any" as a wildcard)
 *   - sg-internet → ["internet"]  (controller built-in)
 *   - everything else → ["<mapKey>"], or fall back to the raw id (UUID) if
 *     not in our local map — the module handles unresolved values as raw UUIDs.
 */
function ruleGroupRef(groupId: string, keyMap: Map<string, string>): string {
  if (groupId === 'sg-any') return '["any"]';
  if (groupId === 'sg-internet') return '["internet"]';
  const k = keyMap.get(groupId);
  return `["${k ?? groupId}"]`;
}

/**
 * Convert a SmartGroup's criteria into the module's selector entries. Each
 * returned string is one selector entry literal (a single `{ ... }` object).
 *
 * Mapping rules:
 *   - subnet criterion → `{ cidr = "..." }`
 *   - vm criterion with key matching a recognized module field (vpc,
 *     account_name, region, etc.) → `{ type = "vpc", name = "..." }` style
 *   - vm criterion with any other key → `{ tags = { key = "value" } }`
 *
 * matchType=all hint: if the source group is matchType=all AND has multiple
 * tag-shaped criteria, those collapse into a single selector entry with a
 * combined tags map (so they AND inside one entry). matchType=any (the
 * default) yields one entry per criterion (OR across entries).
 */
const RECOGNIZED_TYPE_FIELDS = new Set([
  'vpc', 'account_name', 'account_id', 'region', 'zone',
  'res_id', 'site', 'fqdn', 'external', 's2c',
  'k8s_cluster_id', 'k8s_namespace', 'k8s_service', 'k8s_pod',
]);

function buildSmartGroupSelectorEntries(sg: SmartGroup): string[] {
  const entries: string[] = [];
  const tagCriteria: SmartGroupCriteria[] = [];

  for (const c of sg.criteria) {
    if (c.type === 'subnet') {
      if (c.cidr) entries.push(`{ cidr = "${escapeHcl(c.cidr)}" }`);
    } else if (c.type === 'vm') {
      if (c.key && RECOGNIZED_TYPE_FIELDS.has(c.key)) {
        const field = c.key === 'vpc' ? 'type' : c.key; // "vpc" is matched via `type = "vpc"` + name=...
        if (c.key === 'vpc') {
          entries.push(`{ type = "vpc", name = "${escapeHcl(c.value ?? '')}" }`);
        } else {
          entries.push(`{ ${field} = "${escapeHcl(c.value ?? '')}" }`);
        }
      } else if (c.key) {
        tagCriteria.push(c);
      }
    }
  }

  if (tagCriteria.length === 0) return entries;

  if (sg.matchType === 'all') {
    // AND-grouped: one selector entry with all tag pairs combined.
    const pairs = tagCriteria
      .filter((c) => c.key && c.value !== undefined)
      .map((c) => `${c.key} = "${escapeHcl(c.value!)}"`)
      .join(', ');
    entries.push(`{ tags = { ${pairs} } }`);
  } else {
    // OR-grouped: one entry per tag.
    for (const c of tagCriteria) {
      if (!c.key || c.value === undefined) continue;
      entries.push(`{ tags = { ${c.key} = "${escapeHcl(c.value)}" } }`);
    }
  }

  return entries;
}

// Silence the lint about unused WebGroup import (referenced via the topology type).
export type { WebGroup };

export function downloadTerraform(topology: DcfPolicyModel): void {
  const content = generateTerraform(topology);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'aviatrix_dcf.tf';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
