import type { DcfPolicyModel } from '../types/dcf';

function sanitizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '_').replace(/_+/g, '_').replace(/^_+|_+$/g, '');
}

function escapeHcl(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$\{/g, '\\${');
}

function getSmartGroupName(topology: DcfPolicyModel, groupId: string): string | null {
  if (groupId === 'sg-any') return null;
  const sg = topology.smartGroups.find((g) => g.id === groupId);
  return sg?.name || null;
}

export function generateTerraform(topology: DcfPolicyModel): string {
  const lines: string[] = [];

  lines.push(`# Generated by Aviatrix DCF Visualizer`);
  lines.push(`# Terraform configuration for Aviatrix Distributed Cloud Firewall`);
  lines.push(`# Provider: AviatrixSystems/aviatrix (>= 2.22.0)`);
  lines.push('');
  lines.push(`terraform {`);
  lines.push(`  required_providers {`);
  lines.push(`    aviatrix = {`);
  lines.push(`      source  = "AviatrixSystems/aviatrix"`);
  lines.push(`      version = ">= 2.22.0"`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push('');

  // ============================================
  // Smart Groups
  // ============================================
  const exportableSmartGroups = topology.smartGroups.filter(
    (sg) => sg.id !== 'sg-internet' && sg.id !== 'sg-any'
  );

  if (exportableSmartGroups.length > 0) {
    lines.push(`# ============================================`);
    lines.push(`# Smart Groups`);
    lines.push(`# ============================================`);
    lines.push('');

    exportableSmartGroups.forEach((sg) => {
      const resourceName = sanitizeName(sg.name);
      lines.push(`resource "aviatrix_smart_group" "${resourceName}" {`);
      lines.push(`  name = "${escapeHcl(sg.name)}"`);
      lines.push('');

      if (sg.matchType === 'any') {
        sg.criteria.forEach((c) => {
          lines.push(`  selector {`);
          lines.push(`    match_expressions {`);
          if (c.type === 'vm') {
            lines.push(`      type = "vm"`);
            if (c.key) {
              lines.push(`      key  = "tag:${escapeHcl(c.key)}"`);
            }
            if (c.value !== undefined) {
              lines.push(`      val  = "${escapeHcl(c.value)}"`);
            }
          } else if (c.type === 'subnet') {
            lines.push(`      type = "subnet"`);
            if (c.cidr) {
              lines.push(`      cidr = "${escapeHcl(c.cidr)}"`);
            }
          }
          lines.push(`    }`);
          lines.push(`  }`);
        });
      } else {
        lines.push(`  selector {`);
        sg.criteria.forEach((c) => {
          lines.push(`    match_expressions {`);
          if (c.type === 'vm') {
            lines.push(`      type = "vm"`);
            if (c.key) {
              lines.push(`      key  = "tag:${escapeHcl(c.key)}"`);
            }
            if (c.value !== undefined) {
              lines.push(`      val  = "${escapeHcl(c.value)}"`);
            }
          } else if (c.type === 'subnet') {
            lines.push(`      type = "subnet"`);
            if (c.cidr) {
              lines.push(`      cidr = "${escapeHcl(c.cidr)}"`);
            }
          }
          lines.push(`    }`);
        });
        lines.push(`  }`);
      }

      lines.push(`}`);
      lines.push('');
    });
  }

  // ============================================
  // Web Groups
  // ============================================
  if (topology.webGroups.length > 0) {
    lines.push(`# ============================================`);
    lines.push(`# Web Groups`);
    lines.push(`# ============================================`);
    lines.push(`# NOTE: Aviatrix provider does not have a native "aviatrix_web_group" resource.`);
    lines.push(`#       Configure web groups via Controller UI or use aviatrix_fqdn if applicable.`);
    lines.push(`# TODO: Map these web groups to appropriate Terraform resources or data sources.`);
    lines.push('');

    topology.webGroups.forEach((wg) => {
      lines.push(`# WebGroup: ${escapeHcl(wg.name)}`);
      lines.push(`#   FQDNs: ${wg.fqdns.map((f) => escapeHcl(f)).join(', ')}`);
      lines.push('');
    });
  }

  // ============================================
  // Threat Groups (reference only)
  // ============================================
  if (topology.threatGroups.length > 0) {
    lines.push(`# ============================================`);
    lines.push(`# Threat Groups (External Groups)`);
    lines.push(`# ============================================`);
    lines.push(`# Note: Configure ThreatGroups via Controller UI or`);
    lines.push(`#       aviatrix_smart_group with external group selectors.`);
    lines.push('');
  }

  // ============================================
  // Geo Groups (reference only)
  // ============================================
  if (topology.geoGroups.length > 0) {
    lines.push(`# ============================================`);
    lines.push(`# Geo Groups (External Groups)`);
    lines.push(`# ============================================`);
    lines.push(`# Note: Configure GeoGroups via Controller UI.`);
    lines.push('');
  }

  // ============================================
  // DCF Policies
  // ============================================
  lines.push(`# ============================================`);
  lines.push(`# Distributed Cloud Firewall Policies`);
  lines.push(`# ============================================`);
  lines.push('');
  lines.push(`resource "aviatrix_distributed_firewalling_policy_list" "dcf_policies" {`);
  lines.push('');

  topology.policies.forEach((pol) => {
    const srcName = getSmartGroupName(topology, pol.srcGroupId);
    const dstName = getSmartGroupName(topology, pol.dstGroupId);

    const srcExcludeNames = (pol.srcExcludeGroupIds || [])
      .map((id) => getSmartGroupName(topology, id))
      .filter((n): n is string => n !== null);
    const dstExcludeNames = (pol.dstExcludeGroupIds || [])
      .map((id) => getSmartGroupName(topology, id))
      .filter((n): n is string => n !== null);

    const actionMap: Record<string, string> = {
      allow: 'PERMIT',
      deny: 'DENY',
      learned: 'LEARNED',
    };

    lines.push(`  policies {`);
    lines.push(`    # ${escapeHcl(pol.name)} (Priority: ${pol.priority})`);
    lines.push(`    name     = "${escapeHcl(pol.name)}"`);
    lines.push(`    priority = ${pol.priority}`);
    lines.push(`    action   = "${actionMap[pol.action] || 'DENY'}"`);
    lines.push(`    enforce  = ${pol.enforcement !== false}`);
    lines.push(`    protocol = "${pol.protocol.toUpperCase()}"`);
    if (pol.ports && pol.ports !== 'any') {
      lines.push(`    port_ranges = [${pol.ports.split(',').map((p) => `"${escapeHcl(p.trim())}"`).join(', ')}]`);
    }
    lines.push(`    logging = ${pol.logging}`);
    if (pol.decrypt) {
      lines.push(`    decrypt = true`);
    }

    if (srcName) {
      lines.push(`    src_smart_groups = [aviatrix_smart_group.${sanitizeName(srcName)}.name]`);
    } else {
      lines.push(`    src_smart_groups = []`);
    }

    if (dstName) {
      lines.push(`    dst_smart_groups = [aviatrix_smart_group.${sanitizeName(dstName)}.name]`);
    } else {
      lines.push(`    dst_smart_groups = []`);
    }

    if (srcExcludeNames.length > 0) {
      lines.push(
        `    src_exclude_smart_groups = [${srcExcludeNames.map((n) => `aviatrix_smart_group.${sanitizeName(n)}.name`).join(', ')}]`
      );
    }

    if (dstExcludeNames.length > 0) {
      lines.push(
        `    dst_exclude_smart_groups = [${dstExcludeNames.map((n) => `aviatrix_smart_group.${sanitizeName(n)}.name`).join(', ')}]`
      );
    }

    if (pol.webGroupIds && pol.webGroupIds.length > 0) {
      const webGroupNames = pol.webGroupIds
        .map((id) => topology.webGroups.find((wg) => wg.id === id)?.name)
        .filter((n): n is string => !!n);
      if (webGroupNames.length > 0) {
        lines.push(`    # web_groups = [${webGroupNames.map((n) => `"${escapeHcl(n)}"`).join(', ')}]  # TODO: reference once web group resources are defined`);
      }
    }

    if (pol.threatGroup) {
      lines.push(`    threat_group = "${escapeHcl(pol.threatGroup)}"`);
    }
    if (pol.geoGroup) {
      lines.push(`    geo_group = "${escapeHcl(pol.geoGroup)}"`);
    }

    lines.push(`  }`);
    lines.push('');
  });

  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}

export function downloadTerraform(topology: DcfPolicyModel): void {
  const content = generateTerraform(topology);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'aviatrix_dcf.tf';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
